### ISSUE TITLE
Add id to response object

### ISSUE THREAD

**Issue by rui-ribeiro** [andyjeffries/flexirest#12] opened 2016-01-24 00:53 UTC
Hi,

When I call the create service, the service respond with the ID of the new object.

Flexirest, responds the object without the ID, how can i pass the ID?

Thanks

**Comment by andyjeffries** [comment] 2016-01-24 16:26
Can you send me an example of the output of your API so I can test it?  Or a small example that proves your case. Thanks.

**Comment by rui-ribeiro** [comment] 2016-01-24 16:48
The ouput is like : 



```javascript
{
  "status": {
    "code": 201,
    "message": "DEFAULT_SUCCESS"
  },
  "response": {
    "data": "/book/get/263"
  }
}
```

The solution I have found was this (after request):
The scan finds the id

```ruby
response.body = {id: response.body.scan(/\d+$/).first} if name == :save
```

Then on controller
```ruby
redirect_to edit_bank_path(@book._attributes[:id])
```

But I don´t like this work around...

**Comment by andyjeffries** [comment] 2016-01-24 16:53
I don't understand, there is no ID in the response.  If you want it from @book.response.data then I would write a method on your object that does something like this:

```ruby
class Book < Flexirest::Base
  def id
    _attributes.response.data.split("/").last.to_i
  end
end
```

**Comment by rui-ribeiro** [comment] 2016-01-24 17:12
What type of response the plugin expects ?

**Comment by andyjeffries** [comment] 2016-01-24 18:36
If you have a class like this:

```ruby
class Book < Flexirest::Base
   post :create, "/books"
end
```

And you want to use it like this:

```ruby
@book = Book.create(title: "My first book")
puts @book.id
```

Then the response from the `/book` API call should be something like:

```json
{
  "id": 123,
  "status": {
    "code": 201,
    "message": "DEFAULT_SUCCESS"
  },
  "response": {
    "data": "/book/get/263"
  }
}
```

Note it contains an `id` field in the response object.

**Comment by rui-ribeiro** [comment] 2016-01-24 19:06
```ruby
response.body = {id: response.body.scan(/\d+$/).first} if name == :save
```

This code makes that . Replace the body with a json with a key id and the respective ID. I thought that you would expect the id on response so I code that work around but didn´t work.

Thanks for the help

**Comment by andyjeffries** [comment] 2016-01-24 19:23
I don't understand what you mean by "I thought that you would expect the id on response", if an ID comes in the response, Flexirest will make it available, but it can't guess at the logic you want it to use to extract an ID from some random field.

I'll close this issue as Flexirest is behaving as expected/designed.

**Closed by andyjeffries** 2016-01-24 19:23 UTC

**Comment by rui-ribeiro** [comment] 2016-01-26 10:12
Hi!

I have found the problem.
```ruby
attr_accessor :id, :name, :author, :editor
```

I need the attr_accessor to use form_for. How to you handle that?

**Comment by andyjeffries** [comment] 2016-01-26 10:13
Sorry, where is this line of code?  What form_for are you referring to?

I completely don't understand your comment. Sorry.

**Comment by rui-ribeiro** [comment] 2016-01-26 10:14
Is on my book Model.

Form_for:
http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html

**Comment by rui-ribeiro** [comment] 2016-01-26 11:18
The problem was me basically :)

I underestimate your gem. So I was using ActiveModel, and because of that your methods was been override.

To put "form_for"  working i need to 
```ruby
 extend ActiveModel::Naming
  include ActiveModel::Conversion
```

To last questions:

1 - Why you don´t have a update method, only save?
2 - I need to pass a cookie in every request I make, the cookie belongs to user session, when I pass the cookie with the methods params and catch them after request I have to make workarounds. Do you have a cleaner solution to that?

Thanks

**Comment by andyjeffries** [comment] 2016-01-26 11:25
1) You can call the method `update` or `save`, there's no special method for either. It's how you map the API to your class, you can call it whatever you want.

2) REST APIs shouldn't require cookies.  However, an easier way might be to set a header using a `before_request` filter.  There's examples of adding headers at https://github.com/andyjeffries/flexirest#using-filters

**Comment by rui-ribeiro** [comment] 2016-01-26 11:29
```ruby
..
before_request :add_cookie
..
  def add_cookie(name, request)
    cookie = request.method[:method] == :get ? request.get_params.delete(:cookie) : request.post_params.delete(:cookie)
    raise Exceptions::NoCookieFound if cookie.nil?
    request.headers['cookie'] = cookie
  end
```

The problem is:
```ruby
Book.find(id: params[:id], cookie: session[:cookie])
```

**Comment by andyjeffries** [comment] 2016-01-26 11:38
"The problem is", you then give a line of code without saying what the problem is.

If your problem is (I'm guessing) you don't like passing the cookie parameter each time, You could use `cattr_accessor` to set the cookie value on the class, then just have the `before_request` pull out the current value from the class instance variable.  This works if you're not multi-threading.
